config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  # For details on the SL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server, at: '/cable'
  mount Sidekiq::Web => '/sidekiq'
  root to: "pages#index"

  resources :players, except: [:show] do
    member do
      patch :change_status
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
# == Schema Information
#
# Table name: bets
#
#  id                    :bigint           not null, primary key
#  player_id             :bigint           not null
#  round_id              :bigint           not null
#  color                 :integer          not null
#  bet_amount_cents      :integer          default(0), not null
#  bet_amount_currency   :string           default("CLP"), not null
#  prize_amount_cents    :integer          default(0), not null
#  prize_amount_currency :string           default("CLP"), not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#
class Bet < ApplicationRecord
  enum color: { green: 0, red: 1, black: 2 }
  MINIMUN_TO_SET_BET_IN_CENTS = 1_000_00

  ##associations
  belongs_to :player
  belongs_to :round

  #money
  monetize :bet_amount_cents, as: :bet_amount, allow_nil: false
  monetize :prize_amount_cents, as: :prize_amount, allow_nil: true

  ##validations
  validates :player, presence: true, uniqueness: { scope: :round_id, message: "you can't bet more than once per round" }
  validates :round, presence: true
  validates :color, presence: true
  validates :bet_amount, presence: true, numericality: true
  validates :prize_amount, presence: true, numericality: true

  delegate :full_name, to: :player, prefix: :player

  def perform_bet
    self.set_color
    self.set_prize
  end

  private
  def set_color
    probabilities = [
      { color: Bet.colors["green"], probability: 0.02 },
      { color: Bet.colors["red"], probability: 0.49 },
      { color: Bet.colors["black"], probability: 1.00 },
    ]
    random_selection = rand()
    probabilities.each do |p|
      return self.color = p[:color] if random_selection < p[:probability]
    end
  end

  def calculate_bet_amount
    redis = Redis.new
    be_conservative = redis.get("be_conservative")
    unless self.player.balance < Money.new(MINIMUN_TO_SET_BET_IN_CENTS)
      puts Money.new(MINIMUN_TO_SET_BET_IN_CENTS)
      if be_conservative.to_i == 1
        random_bet_percentage = rand(0.03...0.07)
        return self.player.balance * random_bet_percentage
      else
        random_bet_percentage = rand(0.08...0.15)
        return self.player.balance * random_bet_percentage
      end
    end
    return self.player.balance
  end

  def set_prize
    self.bet_amount = calculate_bet_amount
    if self.round.color.to_s == self.color.to_s
      case self.color.to_s
      when "green" 
        self.prize_amount = self.bet_amount * 15
      when "red","black"
        self.prize_amount = self.bet_amount * 2
      end
    end
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id               :bigint           not null, primary key
#  name             :string           not null
#  last_name        :string           not null
#  balance_cents    :integer          default(1000000), not null
#  balance_currency :string           default("CLP"), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  status           :integer          default("active"), not null
#
class Player < ApplicationRecord
  enum status: {inactive: 0, active: 1}

  scope :active_players, -> { where(status: :active) }

  ##associations
  has_many :bets , dependent: :destroy
  has_many :rounds, through: :bets
  accepts_nested_attributes_for :bets

  ##monetize
  monetize :balance_cents, as: :balance

  ##validations
  validates :name, presence: true
  validates :last_name, presence: true
  validates :balance, numericality: true

  def full_name
    "#{self.name} #{self.last_name}"
  end
end

app/models/round.rb
# == Schema Information
#
# Table name: rounds
#
#  id          :bigint           not null, primary key
#  color       :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  started_at  :datetime
#  finished_at :datetime
#
class Round < ApplicationRecord
  enum color: { green: 0, red: 1, black: 2 }

  ##associations
  has_many :bets, dependent: :destroy
  has_many :players, through: :bets
  accepts_nested_attributes_for :bets

  ##validations
  validates :color, presence: true

  def set_color
    probabilities = [
      { color: Round.colors["green"], probability: 0.02 },
      { color: Round.colors["red"], probability: 0.49 },
      { color: Round.colors["black"], probability: 1.00 },
    ]
    random_selection = rand()
    puts random_selection
    selection = probabilities.each do |p|
      if random_selection < p[:probability]
        self.color = p[:color]
        break
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @rounds = Round.order("id DESC").paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, except: [:index, :new, :create]

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create 
    @player = Player.new(create_params)
    respond_to do |format|
      if @player.save
        format.html { redirect_to players_path, notice: "Player was successfully created" }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def edit;end

  def update
    respond_to do |format|
      if @player.update(update_params)
        format.html { redirect_to players_path, notice: "Player was edited successfully" }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @player.destroy
        format.html { redirect_to players_path, notice: "Player was disenrolled successfully" }
      else
        format.html { render :action => "index" }
      end
    end
  end

  def change_status
    respond_to do |format|
      if params[:status].present? && Player.statuses.include?(params[:status])
        if @player.update(status: params[:status])
          format.html { redirect_to players_path, notice: "Player was updated successfully"}
        else
          format.html { redirect_to players_path, alert: "There was a problem, try again" }
        end
      else
        format.html { redirect_to players_path, alert: "There was a problem, try again" }
      end
    end
  end

  private
  def create_params
    params.require(:player).permit(:name, :last_name)
  end

  def update_params
    params.require(:player).permit(:name, :last_name, :balance, :status)
  end

  def set_player
    @player = Player.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
    <% end %>
    <div class="container mt-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<%= render "/pages/index/round_timer" %>
<% unless @rounds.nil? %>
  <div class="row">
    <div class="col-md-12" data-target="rounds_column">
      <% @rounds.each do |round| %>
        <%= render partial: "pages/index/round", locals: { round: round  } %>
      <% end %>
    </div>
  </div>
  <%= will_paginate @rounds %>
<% end %>

app/views/pages/index/_round.html.erb
<div class="card row">
  <div class="col-md-10">
    <h2>Round #<%= round.id%></h2>
  </div>
  <div class="col-2">
    <p>result: <%= round.color %></p>
  </div>
</div>
<table class="table table-striped mb-5">
  <thead>
    <tr>
      <th scope="col">player name</th>
      <th scope="col">player bet</th>
    </tr>
  </thead>
  <tbody>
  <% round.bets.each do |bet| %>
    <%= render partial: "pages/index/round_bet", locals: { bet: bet, round: round} %>
  <% end %>
  </tbody>
</table>

app/views/pages/index/_round_bet.html.erb
<tr>
  <th scope="row"><%= bet.player_full_name %></th>
  <td colspan="2"><%= bet.color %></td>
</tr>

app/views/pages/index/_round_timer.html.erb
<div class="row">
  <div class="col-md-12 card p-5 mb-5">
    <h4>Current round ends in: 3:00</h4>
  </div>
</div>

app/views/players/_actions.html.erb
<%= link_to "Edit", edit_player_path(player), class: "btn btn-warning" %>
<% if player.active? %>
  <%= link_to "Disenroll", change_status_player_path(player, status: :inactive), method: :patch , data: { confirm: "are you sure? this player won't be able to perfom a bet, that means no money for us", disable_with: "disenrolling..." }, class: "btn btn-danger" %>
<% else %>
  <%= link_to "Re Enroll", change_status_player_path(player, status: :active), method: :patch , data: { confirm: "are you sure to allow this player to bet? there is might be a reason why you disenrolled ", disable_with: "re enrolling..." }, class: "btn btn-success" %>
<% end %>

app/views/players/_form.html.erb
<%= form_with model: @player, local: true, html: {class: "card p-5"} do |f| %>
      <div class="form-group mb-2">
        <%= f.text_field :name , class: "form-control", placeholder: "Player name" %>
      </div>
      <div class="form-group mb-2">
        <%= f.text_field :last_name, class: "form-control", placeholder: "Player last name" %>
      </div>
      <% if "edit" == action_name %>
      <div class="form-group mb-2">
        <%= f.text_field :balance, class: "form-control", placeholder: "Player new balance" %>
      </div>
      <% end %>
      <div class="form-group mb-2">
        <%= f.submit class: "btn btn-primary" %>
      </div>
<% end %>

app/views/players/_table_row.html.erb
<tr>
  <th scope="row">#</th>
  <td><%= player.full_name %></td>
  <td><%= humanized_money_with_symbol player.balance %></td>
  <td><%= player.status %></td>
  <td>
    <%= render partial: "players/actions", locals: { player: player} %>
  </td>
</tr>

app/views/players/edit.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Edit a player</h2>
  </div>
  <div class="col-md-2">
    <%= link_to "All players", players_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/players/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>All the players</h2>
  </div>
  <div class="col-md-2">
    <%= link_to "New player", new_player_path, class: "btn btn-primary mr-auto" %>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">balance</th>
      <th scope="col">status</th>
      <th scope="col">actions</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <%= render partial: "players/table_row", locals: {player: player } %>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Enroll a new player</h2>
  </div>
  <div class="col-md-2">
    <%= link_to "All players", players_path, class: "btn btn-primary" %>
  </div>
<div class="row justify-content-center">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Nnodes", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "players", players_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>